theme: jekyll-theme-minimal
title: Xian Li's homepage
description: I am a data scientist passionate about using quantitative techniques to solve real-world problems. Bookmark this to keep an eye on my updates!
